export { default as IconHome } from "./IconHome";
export { default as IconSchedule } from "./IconSchedule";
export { default as IconCommunity } from "./IconCommunity";
export { default as IconLearn } from "./IconLearn";
export { default as IconNote } from "./IconNote";
export { default as IconSetting } from "./IconSetting";
export { default as IconLight } from "./IconLight";
export { default as IconDark } from "./IconDark";
export { default as IconDefault } from "./IconDefault";